---

version: '3.7'
services:

  web:
    command: uvicorn --reload --use-colors --access-log --proxy-headers --log-level info --workers 1 --host 0.0.0.0 --port 8000 app:app
    volumes:
      - type: "bind"
        source: "./web"
        target: "/home/${USER_NAME}/app"


