---

version: '3.7'
services:

  web:
    build:
      args:
        DEPLOY_ENV: ${DEPLOY_ENV}
        USER_NAME: ${USER_NAME}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
      context: "./web/"
      dockerfile: "docker/Dockerfile"

    volumes:
      - type: "bind"
        source: "./web"
        target: "/home/${USER_NAME}/app"

  proxy:
    build:
      context: "./proxy/"
      dockerfile: "Dockerfile"
